@startuml class

abstract class Cliente{
  int id;
  String nome;
  Endereco endereco;
  String telefone;
  String email;
  String obs;

}

class PessoaJuridica {
  int id;
  
  String cnpj;
  String setor;
}

class PessoaFisica{
  int id;

  String cpf;
}

class OrdemServicos{
  Servicos[] servicos;
  Item[] items;

}

class Servico{

}

class Item{
  String nome;
  
}

Cliente <|-- PessoaFisica
Cliente <|-- PessoaJuridica
Servico --* OrdemServicos
Item --* OrdemServicos

@enduml