@startuml class

abstract class Pessoa{
  String id;
  String nome;
  Endereco endereco;
  String telefone;
}

class Funcionario{
  String cpf;
  Cargo cargo;
  Turno turno;
}

class Cargo{
  String id;
  String nome;
  double salario;
}

abstract class Cliente{
  String email;
  String obs;
}

class PessoaJuridica {
  String cnpj;
  String setor;
}

class PessoaFisica{
  String cpf;
}

class OrdemServicos{
  String id;
  Date data;
  StatusOrdemServico status;
  String relatorio;
}

class ItemPecaOS{
  String id;
  int quantidade;
  BigDecimal valorUnitarioCobrado;
  BigDecimal descontoAplicado;
}

class ItemServicoOS{
  String id;
  int quantidade;
  BigDecimal valorCobrado;
}

class Equipamento {
  String marca;
  String modelo;
  String numeroSerie;
  String portaria;
  String numeroInmetro;
  String numeroVerificacao;
  String seloAnterior;
  String seloAtual;
  String lacreAnterior;
  String lacreAtual;
}

class Endereco {
  String id;
  String cep;
  String rua;
  String complemento;
  String cidade;
  String numero;
  String uf;
}

class Servico{
  String id;
  String nome;
  String descricao;
  BigDecimal valorBase;
}

class Peca{
  String id;
  String nome;
  String descricao;
  TipoItem tipo;
  BigDecimal valorBase;
}

enum StatusOrdemServico {
  EM_ORCAMENTO,
  EM_CONSERTO,
  CONCLUIDA,
  ENTREGUE,
  PAGA,
}

class Empresa {
  String cnpj
  String inscricaoMunicipal
  String inscricaoEstadual
  String telefone
  Endereco endereco
}

Pessoa <|-- Cliente
Pessoa <|-- Funcionario
Cliente <|-- PessoaFisica
Cliente <|-- PessoaJuridica

Funcionario --> Cargo

OrdemServicos --> Cliente
OrdemServicos --> Funcionario 

OrdemServicos *-- "1" Equipamento 

OrdemServicos *-- ItemPecaOS 
ItemPecaOS --> Peca 

OrdemServicos *-- ItemServicoOS
ItemServicoOS --> Servico

Pessoa *-- Endereco 
Empresa *-- Endereco 

@enduml