@startuml usecase
left to right direction

' 1. DECLARAÇÃO DOS ATORES (Garante a ordem dos blocos no espaço global)
actor :Funcionário: as func <<Humano>> 
actor :Usuário: as user <<Humano>> 

' 2. ESTRUTURA DO SISTEMA
rectangle "Sistema: Argos" as Argos {
  
  package "Serviço de Login"{
    (Login) as "Entrar como cliente"
    (LoginAdmin) as "Entrar como funcionario"
    (Signin)
  }


  (ClientCRUD) as "Gerenciamento de Clientes"
  (OSCRUD) as "Gerenciamento de OS"
  (PartCRUD) as "Gerenciamento de Estoque"
  (LocalDB) as "Base Interna"
  (ExternalDB) as "Base Externa"
 
}

' 3. LIGAÇÕES ESQUERDA -> CENTRO (Atores Humanos conectando nos Casos de Uso)
user --> Login
user --> Signin
func --> user
func --> LoginAdmin
LoginAdmin --> ClientCRUD
LoginAdmin --> OSCRUD
LoginAdmin --> PartCRUD



' 4. RELACIONAMENTOS INTERNOS


' 5. LIGAÇÕES CENTRO -> DIREITA (Casos de Uso conectando nos Bancos de Dados)
' A seta obrigatoriamente aponta para a direita (-->) partindo do caso de uso para o actor


@enduml
